export { default as Home } from './Home'
export { default as Headphones } from './Headphones'
export { default as Speakers } from './Speakers'
export { default as Earphones } from './Earphones'
export { default as ProductPage } from './ProductPage'
export { default as Checkout } from './Checkout'
export { default as Admin } from './Admin'
